version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: kafka-server-start.sh config/kraft/server.properties
    ports:
      - "9092:9092"
      - "9093:9093"
